### ISSUE TITLE
set_xticklabels on object returned by factorplot with col arg raises IndexError

### ISSUE THREAD

**Issue by jackjackk** [mwaskom/seaborn#599]
---> 36     fg.set_xticklabels(rotation=30)

/usr/lib/python2.7/site-packages/seaborn/axisgrid.pyc in set_xticklabels(self, labels, step, **kwargs)
    585     def set_xticklabels(self, labels=None, step=None, **kwargs):
    586         """Set x axis tick labels on the bottom row of the grid."""
--> 587         for ax in self.axes[-1, :]:
    588             if labels is None:
    589                 labels = [l.get_text() for l in ax.get_xticklabels()]

IndexError: too many indices for array

Thanks,
Giacomo

**Comment by mwaskom** [comment]
Can you please add the code you used to call `factorplot`? It's otherwise very hard to diagnose a problem like this...

**Comment by Winterflower** [comment]
I think, the issue here is that contrary to the Seaborn documentation, the axes attribute of the FacetGrid object returned by factorplot is not of type Axes, but of type numpy.array. 
Since OP does not specify a list of axes labels as parameters in his call to fg.set_xticklabels(rotation=30), 
the Seaborn code tries to do list_comprehension by calling ax.get_xticklabels() which might to something weird given that ax is a numpy array and does not have a get_xticklabels method.

**Comment by mwaskom** [comment]
> I think, the issue here is that contrary to the Seaborn documentation

A pointer to the incorrect documentation would be most helpful

**Comment by mwaskom** [comment]
For the record I think this is the issue that was fixed in https://github.com/mwaskom/seaborn/pull/468 but hard to know for sure.

**Comment by Winterflower** [comment]
@mwaskom 
Sorry I should have linked to the documentation here. 
The page is http://stanford.edu/~mwaskom/software/seaborn/tutorial/axis_grids.html

and the paragraph 

For even more customization, you can work directly with the underling matplotlib Figure and Axes objects, which are stored as member attributes at fig and axes (a two-dimensional array), respectively.

**Comment by mwaskom** [comment]
Yes, it's just confusing because "Axes" is both a singular noun in the context of matplotlib and a plural noun in any other context -- that attribute should probably be `ax_array` (or `axeses`) for more clarity but it's not worth breaking backwards compatibility for.

**Comment by mwaskom** [comment]
I guess the plural of "axes" is "axes, like deer, so maybe it's grammatically correct, but the real lesson here is that English is dumb.

**Comment by Winterflower** [comment]
Yep, apologies to @mwaskom for not reading carefully.
I do however, believe, that OPs original issue is still unresolved and its origin unknown so it might be worth keeping this issue open for the time being (?)
